spring.application.name=demo
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.datasource.url=jdbc:h2:file:C:\\Users\\sabih\\Downloads\chatmemory;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.docker.compose.enabled=true
spring.datasource.username=Sabiha
spring.datasource.password=12345

spring.ai.chat.memory.repository.jdbc.initialize-schema=always


spring.docker.compose.stop.command=down
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=aidemo
